import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { MapPin, Clock, User } from 'lucide-react';
import { safetyService } from '../../services/safetyService';

const STATUS_COLOR = {
    SCHEDULED: 'bg-blue-100 text-blue-700',
    STARTED: 'bg-emerald-100 text-emerald-700',
    IN_PROGRESS: 'bg-emerald-100 text-emerald-700',
    COMPLETED: 'bg-stone-100 text-stone-600',
    CANCELLED: 'bg-red-100 text-red-600',
};

/**
 * Story 5.8 — Public trip-share tracking page.
 * Route: /track/:token  (no auth required)
 * Accessed via the share link generated by the driver.
 */
const PublicTripTracking = () => {
    const { token } = useParams();
    const [trip, setTrip] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        safetyService
            .trackSharedTrip(token)
            .then((res) => setTrip(res.data ?? res))
            .catch((err) => setError(err.message || 'Invalid or expired share link.'))
            .finally(() => setLoading(false));
    }, [token]);

    if (loading)
        return (
            <div className="min-h-screen flex items-center justify-center text-stone-500">
                Loading trip…
            </div>
        );

    if (error)
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center max-w-sm">
                    <div className="text-4xl mb-3">🔗</div>
                    <h2 className="text-xl font-bold text-stone-900 mb-2">Link unavailable</h2>
                    <p className="text-stone-500 text-sm">{error}</p>
                </div>
            </div>
        );

    const statusClass = STATUS_COLOR[trip.status] ?? 'bg-stone-100 text-stone-600';

    return (
        <div className="min-h-screen bg-stone-50 flex flex-col items-center justify-center p-6">
            <div className="w-full max-w-md bg-white rounded-2xl border shadow-sm p-6 space-y-5">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <div className="w-9 h-9 bg-emerald-100 rounded-lg flex items-center justify-center">
                            <MapPin className="w-5 h-5 text-emerald-600" />
                        </div>
                        <div>
                            <p className="text-xs text-stone-400 font-medium uppercase tracking-wide">Live Trip</p>
                            <p className="font-semibold text-stone-800">GreenCommute</p>
                        </div>
                    </div>
                    <span className={`text-xs font-semibold px-3 py-1 rounded-full ${statusClass}`}>
                        {trip.status}
                    </span>
                </div>

                {/* Route */}
                <div className="space-y-3">
                    <div className="flex items-start gap-3">
                        <div className="mt-1 w-3 h-3 rounded-full bg-emerald-500 shrink-0" />
                        <div>
                            <p className="text-xs text-stone-400">From</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.source ?? trip.startLocation ?? '—'}
                            </p>
                        </div>
                    </div>
                    <div className="flex items-start gap-3">
                        <div className="mt-1 w-3 h-3 rounded-full bg-red-500 shrink-0" />
                        <div>
                            <p className="text-xs text-stone-400">To</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.destination ?? trip.endLocation ?? '—'}
                            </p>
                        </div>
                    </div>
                </div>

                {/* Driver */}
                {trip.driver && (
                    <div className="flex items-center gap-3 bg-stone-50 rounded-xl p-3">
                        <div className="w-8 h-8 bg-stone-200 rounded-full flex items-center justify-center">
                            <User className="w-4 h-4 text-stone-500" />
                        </div>
                        <div>
                            <p className="text-xs text-stone-400">Driver</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.driver.name ?? trip.driver.email ?? 'Driver'}
                            </p>
                        </div>
                    </div>
                )}

                {/* Scheduled time */}
                {trip.scheduledTime && (
                    <div className="flex items-center gap-2 text-sm text-stone-500">
                        <Clock className="w-4 h-4 shrink-0" />
                        <span>
                            Scheduled:{' '}
                            {new Date(trip.scheduledTime).toLocaleString(undefined, {
                                dateStyle: 'medium',
                                timeStyle: 'short',
                            })}
                        </span>
                    </div>
                )}

                <p className="text-xs text-stone-400 text-center pt-2 border-t">
                    This link was shared by the trip participant · Shared via GreenCommute
                </p>
            </div>
        </div>
    );
};

export default PublicTripTracking;
