import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { MapPin, Clock, User } from 'lucide-react';
import { safetyService } from '../../services/safetyService';
import LiveTrackingMap from '../../components/LiveTrackingMap';

const STATUS_COLOR = {
    SCHEDULED: 'bg-blue-100 text-blue-700',
    STARTED: 'bg-emerald-100 text-emerald-700',
    IN_PROGRESS: 'bg-emerald-100 text-emerald-700',
    COMPLETED: 'bg-stone-100 text-stone-600',
    CANCELLED: 'bg-red-100 text-red-600',
};

/**
 * Story 5.8 — Public trip-share tracking page.
 * Route: /track/:token  (no auth required)
 * Accessed via the share link generated by the driver.
 */
const PublicTripTracking = () => {
    const { token } = useParams();
    const [trip, setTrip] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        console.log('🔍 [PublicTripTracking] Fetching trip with token:', token);
        safetyService
            .trackSharedTrip(token)
            .then((res) => {
                console.log('✅ [PublicTripTracking] Full API response:', res);
                const result = res.data ?? res;
                console.log('📦 [PublicTripTracking] Response data:', result);
                const tripData = result.trip ?? result;
                console.log('📊 [PublicTripTracking] Extracted trip data:', tripData);
                console.log('📍 [PublicTripTracking] Trip ID:', tripData?._id);
                console.log('🚗 [PublicTripTracking] Driver ID:', tripData?.driverId?._id ?? tripData?.driverId);
                console.log('📋 [PublicTripTracking] Trip status:', tripData?.status);
                console.log('📍 [PublicTripTracking] Source:', tripData?.source);
                console.log('📍 [PublicTripTracking] Destination:', tripData?.destination);
                setTrip(tripData);
            })
            .catch((err) => {
                console.error('❌ [PublicTripTracking] Error fetching trip:', err);
                setError(err.message || 'Invalid or expired share link.');
            })
            .finally(() => setLoading(false));
    }, [token]);

    if (loading)
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="spinner"></div>
            </div>
        );

    if (error) {
        console.error('🔴 [PublicTripTracking] Error state:', error);
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="text-center max-w-sm">
                    <svg className="w-10 h-10 text-stone-300 mx-auto mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13.19 8.688a4.5 4.5 0 0 1 1.242 7.244l-4.5 4.5a4.5 4.5 0 0 1-6.364-6.364l1.757-1.757m9.86-2.556a4.5 4.5 0 0 0-1.242-7.244l-4.5-4.5a4.5 4.5 0 0 0-6.364 6.364L4.343 8.21" /></svg>
                    <h2 className="text-xl font-bold text-stone-900 mb-2">Link unavailable</h2>
                    <p className="text-stone-500 text-sm">{error}</p>
                </div>
            </div>
        );
    }

    if (!trip) {
        console.warn('⚠️ [PublicTripTracking] Trip not loaded yet');
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="spinner"></div>
            </div>
        );
    }

    const statusClass = STATUS_COLOR[trip.status] ?? 'bg-stone-100 text-stone-600';

    if (trip && (trip.status === 'STARTED' || trip.status === 'IN_PROGRESS')) {
        console.log('🗺️ [PublicTripTracking] Rendering live map for trip status:', trip.status);
        return (
            <div className="min-h-screen bg-stone-50 py-8 px-4 animate-fade-in">
                <div className="max-w-6xl mx-auto">
                    {/* Header */}
                    <div className="mb-6">
                        <div className="flex items-center justify-between mb-4 flex-wrap gap-4">
                            <div>
                                <h1 className="text-2xl sm:text-3xl font-bold text-stone-900 tracking-tight">Live Trip Tracking</h1>
                                <p className="text-stone-600 mt-1">Real-time driver location (shared via GreenCommute)</p>
                            </div>
                            <span className={`text-sm font-semibold px-4 py-2 rounded-full ${statusClass}`}>
                                {trip.status === 'STARTED' ? 'In Progress' : 'Completed'}
                            </span>
                        </div>
                    </div>

                    {/* Live Map */}
                    <div className="mb-6">
                        <LiveTrackingMap
                            trip={trip}
                            userRole="public"
                        />
                    </div>

                    {/* Trip Info Card */}
                    <div className="bg-white rounded-lg shadow-md p-6">
                        <h3 className="font-semibold text-stone-900 mb-4">Trip Information</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div>
                                <h4 className="text-sm font-medium text-stone-700 mb-3">Route</h4>
                                <div className="space-y-3">
                                    <div className="flex items-start space-x-2">
                                        <div className="w-3 h-3 bg-green-500 rounded-full mt-1 flex-shrink-0"></div>
                                        <div>
                                            <div className="text-sm text-stone-600">From</div>
                                            <div className="font-medium text-stone-900">{trip.source}</div>
                                        </div>
                                    </div>
                                    <div className="flex items-start space-x-2">
                                        <div className="w-3 h-3 bg-red-500 rounded-full mt-1 flex-shrink-0"></div>
                                        <div>
                                            <div className="text-sm text-stone-600">To</div>
                                            <div className="font-medium text-stone-900">{trip.destination}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <h4 className="text-sm font-medium text-stone-700 mb-3">Driver & Vehicle</h4>
                                <div className="space-y-2">
                                    <div>
                                        <span className="text-sm text-stone-600">Driver:</span>
                                        <p className="font-medium text-stone-900">{trip.driverId?.name || 'Unknown'}</p>
                                    </div>
                                    <div>
                                        <span className="text-sm text-stone-600">Vehicle:</span>
                                        <p className="font-medium text-stone-900">{trip.vehicleType || '—'}</p>
                                    </div>
                                    {trip.scheduledTime && (
                                        <div>
                                            <span className="text-sm text-stone-600">Scheduled:</span>
                                            <p className="font-medium text-stone-900">
                                                {new Date(trip.scheduledTime).toLocaleString()}
                                            </p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-stone-50 flex flex-col items-center justify-center p-6">
            <div className="w-full max-w-md bg-white rounded-2xl border shadow-sm p-6 space-y-5">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <div className="w-9 h-9 bg-emerald-100 rounded-lg flex items-center justify-center">
                            <MapPin className="w-5 h-5 text-emerald-600" />
                        </div>
                        <div>
                            <p className="text-xs text-stone-400 font-medium uppercase tracking-wide">Live Trip</p>
                            <p className="font-semibold text-stone-800">GreenCommute</p>
                        </div>
                    </div>
                    <span className={`text-xs font-semibold px-3 py-1 rounded-full ${statusClass}`}>
                        {trip.status}
                    </span>
                </div>

                {/* Route */}
                <div className="space-y-3">
                    <div className="flex items-start gap-3">
                        <div className="mt-1 w-3 h-3 rounded-full bg-emerald-500 shrink-0" />
                        <div>
                            <p className="text-xs text-stone-400">From</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.source ?? trip.startLocation ?? '—'}
                            </p>
                        </div>
                    </div>
                    <div className="flex items-start gap-3">
                        <div className="mt-1 w-3 h-3 rounded-full bg-red-500 shrink-0" />
                        <div>
                            <p className="text-xs text-stone-400">To</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.destination ?? trip.endLocation ?? '—'}
                            </p>
                        </div>
                    </div>
                </div>

                {/* Driver */}
                {trip.driver && (
                    <div className="flex items-center gap-3 bg-stone-50 rounded-xl p-3">
                        <div className="w-8 h-8 bg-stone-200 rounded-full flex items-center justify-center">
                            <User className="w-4 h-4 text-stone-500" />
                        </div>
                        <div>
                            <p className="text-xs text-stone-400">Driver</p>
                            <p className="text-sm font-medium text-stone-800">
                                {trip.driver.name ?? trip.driver.email ?? 'Driver'}
                            </p>
                        </div>
                    </div>
                )}

                {/* Scheduled time */}
                {trip.scheduledTime && (
                    <div className="flex items-center gap-2 text-sm text-stone-500">
                        <Clock className="w-4 h-4 shrink-0" />
                        <span>
                            Scheduled:{' '}
                            {new Date(trip.scheduledTime).toLocaleString(undefined, {
                                dateStyle: 'medium',
                                timeStyle: 'short',
                            })}
                        </span>
                    </div>
                )}

                <p className="text-xs text-stone-400 text-center pt-2 border-t">
                    This link was shared by the trip participant · Shared via GreenCommute
                </p>
            </div>
        </div>
    );
};

export default PublicTripTracking;
